name: test workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: First job
        run: |
          echo "first yaml"
          git checkout main
          git merge master
